import { Geist, Geist_Mono, Inter, Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import { ThemeProvider } from 'next-themes';
import NextTopLoader from 'nextjs-toploader';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
});

const outfit = Outfit({
    subsets: ['latin'],
    variable: '--font-outfit',
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        // 1. ADDED suppressHydrationWarning (Required by next-themes)
        <html
            lang="en"
            className={`${inter.variable} ${outfit.variable}`}
            suppressHydrationWarning
        >
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                >
                    <NextTopLoader
                        color="var(--nice-blue)"
                        initialPosition={0.08}
                        crawlSpeed={200}
                        height={3}
                        crawl={true}
                        showSpinner={false}
                        easing="ease"
                        speed={200}
                        shadow="0 0 10px var(--nice-blue), 0 0 5px var(--nice-blue)"
                    />

                    {children}

                    <Toaster
                        position="top-center"
                        containerStyle={{ zIndex: 99999 }}
                    />
                </ThemeProvider>
            </body>
        </html>
    );
}