import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import { Inter, Outfit } from 'next/font/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
});

const outfit = Outfit({
    subsets: ['latin'],
    variable: '--font-outfit',
});

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${inter.variable} ${outfit.variable}`}>
            <body>
            <script dangerouslySetInnerHTML={{
                __html: `
                        (function() {
                            const saved = localStorage.getItem('theme');
                            const system = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                            document.body.classList.add(saved || system);
                        })()
                    `
            }} />
                {children}
                <Toaster
                    position="top-center"
                    containerStyle={{ zIndex: 99999 }}
                />
            </body>
        </html>
    );
}

<Toaster
    position="top-center"
    containerStyle={{
        zIndex: 99999,
    }}
/>
